### ISSUE TITLE
Connects to 127.0.0.1

### ISSUE THREAD

**Issue by pvijaysimha** [Level-2/Synket#1]
It seems, the client always connects to local IP. Not sure where I went wrong?

myserverip is Java socket server IP

const Synket = require('synket');

try{
    var connection = new Synket({url: 'myserverip', port: 9811});

    var result = connection.send('command-to-get-somedata');

    console.log(result);

}catch(err){
    console.log(err);
}

Error: connect ECONNREFUSED 127.0.0.1:9811
 at Object.exports._errnoException (util.js:1029:11)
    at exports._exceptionWithHostPort (util.js:1052:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

    at Object.send (/home/vijay/Work/RSS/backofficenode/node_modules/synket/src/Synket.js:22:10)
    at Object.<anonymous> (/home/vijay/Work/RSS/backofficenode/services/util/socketService.js:7:29)

**Comment by devarajchidambaram** [comment]
Yes Im too facing the same error ..Its connects always to local ip

**Comment by devarajchidambaram** [comment]
Need to update in docs instead of **url** use **host**, it will work fine

var connection = new Synket({**url**: 'http://example.org', port: 4564});

var connection = new Synket({**host**: 'http://example.org', port: 4564});

**Comment by devarajchidambaram** [comment]
I sent the merge request please update the changes
